### ISSUE TITLE
观摩大佬

### ISSUE THREAD

**Issue by Ran-Xing** [CloudSecretBase/xiaomo-k8s-workshop#1]
拉我

**Comment by houko** [comment]
@Ran-Xing  done

**Comment by Ran-Xing** [comment]
@here 🤣
<img width="396" alt="image" src="https://user-images.githubusercontent.com/73819467/203310118-dcc1522f-10e4-4287-9ff0-b0b1cd04b74d.png">

**Comment by Ran-Xing** [comment]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/73819467/203310219-a9eb9f02-7533-43a1-b092-ed039a43b671.png">
